In [65]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

In [66]:
df = pd.read_csv("Gaming Survey Evaluation.csv")
if 'Timestamp' in df.columns:
    df = df.drop(columns=['Timestamp'])
df.head(10)

,Gender / เพศ,Age / อายุ,Status / สถานะ,Do you play games? / คุณเล่นเกมหรือไม่,Why do you play games? / คุณเล่นเกมเพื่ออะไร,How many hours do you play games per day? / คุณเล่นเกมกี่ชั่วโมงต่อวัน,What time do you usually play games? / คุณเล่นเกมช่วงเวลาใดมากที่สุด,Which platform do you use? / คุณเล่นเกมผ่านแพลตฟอร์มใด,What genres do you play? / คุณเคยเล่นเกมแนวไหนมาบ้าง,What genre do you play the most? / คุณชอบเล่นแนวไหนมากที่สุด,...,How much do you spend on games per month? / คุณใช้เงินกับเกมต่อเดือนเท่าไหร่,What do you usually spend money on? / คุณใช้เงินไปกับอะไร,Do you think you play games too much? / คุณคิดว่าคุณเล่นเกมมากเกินไปหรือไม่,Does gaming affect your study/work? / การเล่นเกมมีผลต่อการเรียน/การทำงานหรือไม่,How many hours do you sleep per day? / คุณนอนกี่ชั่วโมงต่อวัน,Do you play games before sleeping? / คุณเล่นเกมก่อนนอนไหม,Does gaming affect your health? / การเล่นเกมส่งผลต่อสุขภาพหรือไม่,Have you ever tried to reduce your gaming time but failed? / คุณเคยพยายามลดเวลาเล่นเกม แต่ไม่สำเร็จหรือไม่,Do you feel irritated when you cannot play games? / คุณรู้สึกหงุดหงิดเมื่อไม่ได้เล่นเกมหรือไม่,Do you neglect responsibilities because of gaming? / คุณเคยละเลยหน้าที่ (เช่น การเรียน งาน หรือกิจกรรมอื่นๆ) เพราะการเล่นเกมหรือไม่
0,Male / ชาย,18 - 20,"Student / นักเรียน , นักศึกษา",Yes / เล่น,Socializing with friends / เล่นกับเพื่อน,1-2 hours / 1-2 ชั่วโมง,์Night / กลางคืน,"Mobile / มือถือ, PC / Laptop","MOBA (Ex. ROV, Dota, MLBB, League Of Legend), ...","MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,100–500 THB,Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),Not at all / ไม่เลย,Not at all / ไม่เลย,NaN,NaN,Sleep issues / นอนดึก,NaN,NaN,NaN
1,Male / ชาย,18 - 20,"Student / นักเรียน , นักศึกษา",Yes / เล่น,Socializing with friends / เล่นกับเพื่อน,More than 6 hours / มากกว่า 6 ชั่วโมง,Night / กลางคืน,PC / Laptop,"Action / Shooting (Ex. Apex Legends, Valorant,...","Action / Shooting (Ex. Apex Legend, Valorant, ...",...,Less than 100 THB / ต่ำกว่า 100 บาท,Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),A lot / มาก,A lot / มาก,7-8 hour / 7-8 ชั่วโมง,Yes / เล่น,Eye strain / ปวดตา,Sometimes / บางครั้ง,Sometimes / บางครั้ง,Often / บ่อย
2,Male / ชาย,21 - 23,Other / อื่นๆ,Yes / เล่น,Socializing with friends / เล่นกับเพื่อน,3-4 hours / 3-4 ชั่วโมง,Afternoon / บ่าย,Mobile / มือถือ,"MOBA (Ex. ROV, Dota, MLBB, League Of Legends),...","MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,100–500 THB,Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),Moderately / ปานกลาง,Moderately / ปานกลาง,7-8 hour / 7-8 ชั่วโมง,Yes / เล่น,Sleep issues / นอนดึก,Sometimes / บางครั้ง,Never / ไม่เคย,Sometimes / บางครั้ง
3,Female / หญิง,18 - 20,"Student / นักเรียน , นักศึกษา",Yes / เล่น,NaN,5-6 hours / 5-6 ชั่วโมง,Night / กลางคืน,PC / Laptop,"Action / Shooting (Ex. Apex Legends, Valorant,...","Action / Shooting (Ex. Apex Legend, Valorant, ...",...,"More than 1,000 THB / มากกว่า 1,000 บาท",Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),A lot / มาก,Not at all / ไม่เลย,Less than 4 hour / น้อยกว่า 4 ชั่วโมง,Yes / เล่น,Back/neck pain / ปวดหลัง/คอ,Sometimes / บางครั้ง,Sometimes / บางครั้ง,Sometimes / บางครั้ง
4,Male / ชาย,24 +,"Student / นักเรียน , นักศึกษา",Yes / เล่น,Achievement / ความสำเร็จในเกม,3-4 hours / 3-4 ชั่วโมง,Afternoon / บ่าย,Mobile / มือถือ,"MOBA (Ex. ROV, Dota, MLBB, League Of Legends),...","MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,"More than 1,000 THB / มากกว่า 1,000 บาท",Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),A lot / มาก,Not at all / ไม่เลย,5-6 hour / 5-6 ชั่วโมง,Yes / เล่น,Eye strain / ปวดตา,Never / ไม่เคย,Sometimes / บางครั้ง,Never / ไม่เคย
5,Female / หญิง,18 - 20,"Student / นักเรียน , นักศึกษา",Yes / เล่น,Relaxation / ผ่อนคลาย,Less than 1 hour / น้อยกว่า 1 ชั่วโมง,Night / กลางคืน,Mobile / มือถือ,"Simulation (Ex. The Sims, Animal Crossing, Sta...","MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,Less than 100 THB / ต่ำกว่า 100 บาท,Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),Not at all / ไม่เลย,Not at all / ไม่เลย,5-6 hour / 5-6 ชั่วโมง,Yes / เล่น,No effect / ไม่ส่งผล,Never / ไม่เคย,Never / ไม่เคย,Never / ไม่เคย
6,Female / หญิง,24 +,"Student / นักเรียน , นักศึกษา",Yes / เล่น,Socializing with friends / เล่นกับเพื่อน,More than 6 hours / มากกว่า 6 ชั่วโมง,Morning / เช้า,Mobile / มือถือ,"MOBA (Ex. ROV, Dota, MLBB, League Of Legends),...","RPG (Ex. Genshin impact, Elden Ring, Black Des...",...,Less than 100 THB / ต่ำกว่า 100 บาท,Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),A lot / มาก,Slightly / เล็กน้อย,7-8 hour / 7-8 ชั่วโมง,Yes / เล่น,Sleep issues / นอนดึก,Sometimes / บางครั้ง,Sometimes / บางครั้ง,Never / ไม่เคย
7,Male / ชาย,24 +,Working / ทำงาน,Yes / เล่น,Competition / แข่งขัน,More than 6 hours / มากกว่า 6 ชั่วโมง,Afternoon / บ่าย,PC / Laptop,"Action / Shooting (Ex. Apex Legends, Valorant,...","Action / Shooting (Ex. Apex Legend, Valorant, ...",...,"More than 1,000 THB / มากกว่า 1,000 บาท",Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),A lot / มาก,Slightly / เล็กน้อย,5-6 hour / 5-6 ชั่วโมง,Yes / เล่น,Eye strain / ปวดตา,Sometimes / บางครั้ง,Sometimes / บางครั้ง,Sometimes / บางครั้ง
8,Female / หญิง,24 +,Working / ทำงาน,Yes / เล่น,Relaxation / ผ่อนคลาย,1-2 hours / 1-2 ชั่วโมง,Night / กลางคืน,"Mobile / มือถือ, PC / Laptop","Action / Shooting (Ex. Apex Legends, Valorant,...","RPG (Ex. Genshin impact, Elden Ring, Black Des...",...,"More than 1,000 THB / มากกว่า 1,000 บาท",Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),A lot / มาก,Not at all / ไม่เลย,7-8 hour / 7-8 ชั่วโมง,Yes / เล่น,Back/neck pain / ปวดหลัง/คอ,Sometimes / บางครั้ง,Never / ไม่เคย,Never / ไม่เคย
9,Other / อื่นๆ,18 - 20,"Student / นักเรียน , นักศึกษา",Yes / เล่น,Relaxation / ผ่อนคลาย,3-4 hours / 3-4 ชั่วโมง,Night / กลางคืน,"Mobile / มือถือ, PC / Laptop","Action / Shooting (Ex. Apex Legends, Valorant,...","MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,"500–1,000 THB",Skins / Cosmetic (สกิน / ของตกแต่งภายในเกม),Not at all / ไม่เลย,Not at all / ไม่เลย,Less than 4 hour / น้อยกว่า 4 ชั่วโมง,Yes / เล่น,Sleep issues / นอนดึก,Never / ไม่เคย,Never / ไม่เคย,Sometimes / บางครั้ง

# Data Cleaning Tech #1 only English

In [67]:
new_column_names = {
    'Gender / เพศ': 'Gender',
    'Age / อายุ': 'Age',
    'Do you play games? / คุณเล่นเกมหรือไม่  ': 'Plays_Games',
    'How many hours do you play games per day? / คุณเล่นเกมกี่ชั่วโมงต่อวัน': 'Game_Hours',
    'Which platform do you use? / คุณเล่นเกมผ่านแพลตฟอร์มใด': 'Platform',
    'Does gaming affect your study/work? / การเล่นเกมมีผลต่อการเรียน/การทำงานหรือไม่': 'Impact_on_Work',
    'How many hours do you sleep per day? / คุณนอนกี่ชั่วโมงต่อวัน': 'Sleep_Hours',
    'How much do you spend on games per month? / คุณใช้เงินกับเกมต่อเดือนเท่าไหร่': 'Spending_on_Games',
    'Does gaming affect your health? / การเล่นเกมส่งผลต่อสุขภาพหรือไม่': 'Impact_on_Health'
}
df.rename(columns=new_column_names, inplace=True)

In [68]:
def keep_english_only(text):
    if isinstance(text, str) and '/' in text:
        return text.split('/')[0].strip()
    return text

In [69]:
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(keep_english_only)

In [70]:
df[['Gender', 'Game_Hours', 'Impact_on_Work', 'Sleep_Hours', 'Plays_Games', 'Platform', 'Age', 'Spending_on_Games', 'Impact_on_Health']].head(10)

,Gender,Game_Hours,Impact_on_Work,Sleep_Hours,Plays_Games,Platform,Age,Spending_on_Games,Impact_on_Health
0,Male,1-2 hours,Not at all,NaN,Yes,Mobile,18 - 20,100–500 THB,Sleep issues
1,Male,More than 6 hours,A lot,7-8 hour,Yes,PC,18 - 20,Less than 100 THB,Eye strain
2,Male,3-4 hours,Moderately,7-8 hour,Yes,Mobile,21 - 23,100–500 THB,Sleep issues
3,Female,5-6 hours,Not at all,Less than 4 hour,Yes,PC,18 - 20,"More than 1,000 THB",Back
4,Male,3-4 hours,Not at all,5-6 hour,Yes,Mobile,24 +,"More than 1,000 THB",Eye strain
5,Female,Less than 1 hour,Not at all,5-6 hour,Yes,Mobile,18 - 20,Less than 100 THB,No effect
6,Female,More than 6 hours,Slightly,7-8 hour,Yes,Mobile,24 +,Less than 100 THB,Sleep issues
7,Male,More than 6 hours,Slightly,5-6 hour,Yes,PC,24 +,"More than 1,000 THB",Eye strain
8,Female,1-2 hours,Not at all,7-8 hour,Yes,Mobile,24 +,"More than 1,000 THB",Back
9,Other,3-4 hours,Not at all,Less than 4 hour,Yes,Mobile,18 - 20,"500–1,000 THB",Sleep issues

# Data Cleaning Tech #2 Missing Values

In [71]:
df.isnull().sum()

Gender                                                                                                                                   0
Age                                                                                                                                      0
Status / สถานะ                                                                                                                           0
Plays_Games                                                                                                                              0
Why do you play games? / คุณเล่นเกมเพื่ออะไร                                                                                             2
Game_Hours                                                                                                                               0
What time do you usually play games? / คุณเล่นเกมช่วงเวลาใดมากที่สุด                                                                     2
Platform                                                                                                                                 3
What genres do you play? / คุณเคยเล่นเกมแนวไหนมาบ้าง                                                                                     1
What genre do you play the most? / คุณชอบเล่นแนวไหนมากที่สุด                                                                             1
Have you ever spent money on games? / คุณเคยเติมเงินในเกมหรือไม่                                                                         1
Spending_on_Games                                                                                                                        0
What do you usually spend money on? / คุณใช้เงินไปกับอะไร                                                                                1
Do you think you play games too much? / คุณคิดว่าคุณเล่นเกมมากเกินไปหรือไม่                                                              1
Impact_on_Work                                                                                                                           0
Sleep_Hours                                                                                                                              1
Do you play games before sleeping?  / คุณเล่นเกมก่อนนอนไหม                                                                               1
Impact_on_Health                                                                                                                         0
Have you ever tried to reduce your gaming time but failed? / คุณเคยพยายามลดเวลาเล่นเกม แต่ไม่สำเร็จหรือไม่                               1
Do you feel irritated when you cannot play games? /  คุณรู้สึกหงุดหงิดเมื่อไม่ได้เล่นเกมหรือไม่                                          1
Do you neglect responsibilities because of gaming? /  คุณเคยละเลยหน้าที่ (เช่น การเรียน งาน หรือกิจกรรมอื่นๆ) เพราะการเล่นเกมหรือไม่     1
dtype: int64

In [72]:
df.dropna(inplace=True)

In [73]:
df.isnull().sum()

Gender                                                                                                                                   0
Age                                                                                                                                      0
Status / สถานะ                                                                                                                           0
Plays_Games                                                                                                                              0
Why do you play games? / คุณเล่นเกมเพื่ออะไร                                                                                             0
Game_Hours                                                                                                                               0
What time do you usually play games? / คุณเล่นเกมช่วงเวลาใดมากที่สุด                                                                     0
Platform                                                                                                                                 0
What genres do you play? / คุณเคยเล่นเกมแนวไหนมาบ้าง                                                                                     0
What genre do you play the most? / คุณชอบเล่นแนวไหนมากที่สุด                                                                             0
Have you ever spent money on games? / คุณเคยเติมเงินในเกมหรือไม่                                                                         0
Spending_on_Games                                                                                                                        0
What do you usually spend money on? / คุณใช้เงินไปกับอะไร                                                                                0
Do you think you play games too much? / คุณคิดว่าคุณเล่นเกมมากเกินไปหรือไม่                                                              0
Impact_on_Work                                                                                                                           0
Sleep_Hours                                                                                                                              0
Do you play games before sleeping?  / คุณเล่นเกมก่อนนอนไหม                                                                               0
Impact_on_Health                                                                                                                         0
Have you ever tried to reduce your gaming time but failed? / คุณเคยพยายามลดเวลาเล่นเกม แต่ไม่สำเร็จหรือไม่                               0
Do you feel irritated when you cannot play games? /  คุณรู้สึกหงุดหงิดเมื่อไม่ได้เล่นเกมหรือไม่                                          0
Do you neglect responsibilities because of gaming? /  คุณเคยละเลยหน้าที่ (เช่น การเรียน งาน หรือกิจกรรมอื่นๆ) เพราะการเล่นเกมหรือไม่     0
dtype: int64

# Data Transform Tech #1 Ordinal Mapping

In [74]:
def convert_hours(text):
    if '1-2' in text: return 1.5
    if '3-4' in text: return 3.5
    if '5-6' in text: return 5.5
    if '7-8' in text: return 7.5
    if 'Less than' in text or '1' in text: return 0.5
    if 'More than' in text or '6' in text: return 6
    return 0

In [75]:
df['Game_Hours_Num'] = df['Game_Hours'].astype(str).apply(convert_hours)
df['Sleep_Hours_Num'] = df['Sleep_Hours'].astype(str).apply(convert_hours)

In [76]:
df_cleaned = df.drop(['Game_Hours', 'Sleep_Hours'], axis=1)

In [77]:
df.head(10)

,Gender,Age,Status / สถานะ,Plays_Games,Why do you play games? / คุณเล่นเกมเพื่ออะไร,Game_Hours,What time do you usually play games? / คุณเล่นเกมช่วงเวลาใดมากที่สุด,Platform,What genres do you play? / คุณเคยเล่นเกมแนวไหนมาบ้าง,What genre do you play the most? / คุณชอบเล่นแนวไหนมากที่สุด,...,Do you think you play games too much? / คุณคิดว่าคุณเล่นเกมมากเกินไปหรือไม่,Impact_on_Work,Sleep_Hours,Do you play games before sleeping? / คุณเล่นเกมก่อนนอนไหม,Impact_on_Health,Have you ever tried to reduce your gaming time but failed? / คุณเคยพยายามลดเวลาเล่นเกม แต่ไม่สำเร็จหรือไม่,Do you feel irritated when you cannot play games? / คุณรู้สึกหงุดหงิดเมื่อไม่ได้เล่นเกมหรือไม่,Do you neglect responsibilities because of gaming? / คุณเคยละเลยหน้าที่ (เช่น การเรียน งาน หรือกิจกรรมอื่นๆ) เพราะการเล่นเกมหรือไม่,Game_Hours_Num,Sleep_Hours_Num
1,Male,18 - 20,Student,Yes,Socializing with friends,More than 6 hours,Night,PC,Action,Action,...,A lot,A lot,7-8 hour,Yes,Eye strain,Sometimes,Sometimes,Often,6.0,7.5
2,Male,21 - 23,Other,Yes,Socializing with friends,3-4 hours,Afternoon,Mobile,"MOBA (Ex. ROV, Dota, MLBB, League Of Legends),...","MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,Moderately,Moderately,7-8 hour,Yes,Sleep issues,Sometimes,Never,Sometimes,3.5,7.5
4,Male,24 +,Student,Yes,Achievement,3-4 hours,Afternoon,Mobile,"MOBA (Ex. ROV, Dota, MLBB, League Of Legends),...","MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,A lot,Not at all,5-6 hour,Yes,Eye strain,Never,Sometimes,Never,3.5,5.5
5,Female,18 - 20,Student,Yes,Relaxation,Less than 1 hour,Night,Mobile,"Simulation (Ex. The Sims, Animal Crossing, Sta...","MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,Not at all,Not at all,5-6 hour,Yes,No effect,Never,Never,Never,0.5,5.5
6,Female,24 +,Student,Yes,Socializing with friends,More than 6 hours,Morning,Mobile,"MOBA (Ex. ROV, Dota, MLBB, League Of Legends),...","RPG (Ex. Genshin impact, Elden Ring, Black Des...",...,A lot,Slightly,7-8 hour,Yes,Sleep issues,Sometimes,Sometimes,Never,6.0,7.5
7,Male,24 +,Working,Yes,Competition,More than 6 hours,Afternoon,PC,Action,Action,...,A lot,Slightly,5-6 hour,Yes,Eye strain,Sometimes,Sometimes,Sometimes,6.0,5.5
8,Female,24 +,Working,Yes,Relaxation,1-2 hours,Night,Mobile,Action,"RPG (Ex. Genshin impact, Elden Ring, Black Des...",...,A lot,Not at all,7-8 hour,Yes,Back,Sometimes,Never,Never,1.5,7.5
9,Other,18 - 20,Student,Yes,Relaxation,3-4 hours,Night,Mobile,Action,"MOBA (Ex. ROV, Dota, MLBB, League Of Legend)",...,Not at all,Not at all,Less than 4 hour,Yes,Sleep issues,Never,Never,Sometimes,3.5,0.5
10,Female,21 - 23,Working,Yes,Relaxation,Less than 1 hour,Night,Mobile,Action,Action,...,Not at all,Not at all,7-8 hour,Yes,No effect,Never,Never,Never,0.5,7.5
11,Female,18 - 20,Student,Yes,Socializing with friends,Less than 1 hour,Night,Mobile,Action,Action,...,Not at all,Slightly,5-6 hour,Yes,Eye strain,Sometimes,Never,Sometimes,0.5,5.5

In [78]:
le = LabelEncoder()
categorical_cols = df_cleaned.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df_cleaned[col] = le.fit_transform(df_cleaned[col].astype(str))
    
df_cleaned.head(10)

,Gender,Age,Status / สถานะ,Plays_Games,Why do you play games? / คุณเล่นเกมเพื่ออะไร,What time do you usually play games? / คุณเล่นเกมช่วงเวลาใดมากที่สุด,Platform,What genres do you play? / คุณเคยเล่นเกมแนวไหนมาบ้าง,What genre do you play the most? / คุณชอบเล่นแนวไหนมากที่สุด,Have you ever spent money on games? / คุณเคยเติมเงินในเกมหรือไม่,...,What do you usually spend money on? / คุณใช้เงินไปกับอะไร,Do you think you play games too much? / คุณคิดว่าคุณเล่นเกมมากเกินไปหรือไม่,Impact_on_Work,Do you play games before sleeping? / คุณเล่นเกมก่อนนอนไหม,Impact_on_Health,Have you ever tried to reduce your gaming time but failed? / คุณเคยพยายามลดเวลาเล่นเกม แต่ไม่สำเร็จหรือไม่,Do you feel irritated when you cannot play games? / คุณรู้สึกหงุดหงิดเมื่อไม่ได้เล่นเกมหรือไม่,Do you neglect responsibilities because of gaming? / คุณเคยละเลยหน้าที่ (เช่น การเรียน งาน หรือกิจกรรมอื่นๆ) เพราะการเล่นเกมหรือไม่,Game_Hours_Num,Sleep_Hours_Num
1,1,0,1,1,4,2,1,0,0,1,...,4,0,0,1,1,2,2,1,6.0,7.5
2,1,1,0,1,4,0,0,5,2,1,...,4,1,1,1,3,2,0,2,3.5,7.5
4,1,2,1,1,0,0,0,3,2,1,...,4,0,2,1,1,0,2,0,3.5,5.5
5,0,0,1,1,3,2,0,21,2,1,...,4,2,2,1,2,0,0,0,0.5,5.5
6,0,2,1,1,4,1,0,3,4,1,...,4,0,3,1,3,2,2,0,6.0,7.5
7,1,2,2,1,1,0,1,0,0,1,...,4,0,3,1,1,2,2,2,6.0,5.5
8,0,2,2,1,3,2,0,0,4,1,...,4,0,2,1,0,2,0,0,1.5,7.5
9,2,0,1,1,3,2,0,0,2,1,...,4,2,2,1,3,0,0,2,3.5,0.5
10,0,1,2,1,3,2,0,0,0,1,...,2,2,2,1,2,0,0,0,0.5,7.5
11,0,0,1,1,4,2,0,0,0,1,...,4,2,3,1,1,2,0,2,0.5,5.5

# Fit Model + Prediction (Random Forest)

In [79]:
df_model = df.copy()
X = df_model.drop('Impact_on_Health', axis=1)
y = df_model['Impact_on_Health']

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Male'

In [ ]:
y_pred = model.predict(X_test)

AttributeError: 'RandomForestClassifier' object has no attribute 'estimators_'

In [ ]:
print(classification_report(y_test, y_pred))

NameError: name 'y_pred' is not defined